// <auto-generated />
using System;
using CampanhaInfopharma.EFContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CampanhaInfopharma.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CampanhaInfopharma.Models.ContatoDrogaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAlteracao");

                    b.Property<int>("DrogariaIdFk");

                    b.Property<string>("Observacao");

                    b.Property<int>("Status");

                    b.Property<int>("TipoProposta");

                    b.HasKey("Id");

                    b.HasIndex("DrogariaIdFk");

                    b.ToTable("ContatoDrogaria");
                });

            modelBuilder.Entity("CampanhaInfopharma.Models.Drogaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18);

                    b.Property<string>("Cidade")
                        .IsRequired();

                    b.Property<string>("Estado")
                        .IsRequired();

                    b.Property<int?>("FuncionarioIdFk");

                    b.Property<string>("NomeContato");

                    b.Property<string>("NomeFantasia")
                        .IsRequired();

                    b.Property<string>("RazaoSocial")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioIdFk");

                    b.ToTable("Drogaria");
                });

            modelBuilder.Entity("CampanhaInfopharma.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorMarcacao");

                    b.Property<string>("Login");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("CampanhaInfopharma.Models.ContatoDrogaria", b =>
                {
                    b.HasOne("CampanhaInfopharma.Models.Drogaria", "Drogaria")
                        .WithMany()
                        .HasForeignKey("DrogariaIdFk")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CampanhaInfopharma.Models.Drogaria", b =>
                {
                    b.HasOne("CampanhaInfopharma.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioIdFk");
                });
#pragma warning restore 612, 618
        }
    }
}
